name: Compile source code and release
env:
    OUTPUT_BRANCH: release
    OUTPUT: wiemantheme.theme.css

on:
    push:
        branches:
            - master

jobs:
    build-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install

            - name: Compile SCSS
              run: npm run compile

            - name: Commit changes
              run: |
                  git config --global user.name 'wiemanboy'
                  git config --global user.email 'wiemanboy@gmail.com'
                  git checkout -b $OUTPUT_BRANCH

                  rm -rf .github
                  rm -rf node_modules
                  rm -rf src
                  rm -rf .gitignore
                  rm -rf .prettierrc
                  rm -rf package.json
                  rm -rf package-lock.json
                  rm -rf README.md
                  rm -rf $OUTPUT.map


                  git add .
                  git commit -m "Compile SCSS"
                  git push -f origin $OUTPUT_BRANCH

            - name: Create release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: "${{ secrets.TOKEN }}"
                  automatic_release_tag: ${{ vars.NEXT_VERSION }}
                  prerelease: false
                  title: "WiemanTheme ${{ vars.NEXT_VERSION }}"
                  files: ${{ env.OUTPUT }}
