name: Compile source code and release
env:
  OUTPUT_BRANCH: release
  OUTPUT: wiemantheme.theme.css

on:
  push:
    branches:
      - master

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Compile SCSS
        run: npm run compile -- name="${{ github.event.repository.name }}" author="${{ github.repository_owner }}" description="${{ vars.DESCRIPTION }}" source="${{ github.event.repository.html_url }}"

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git config --global user.name ${{ github.triggering_actor }}.
          git config --global user.email ${{ github.triggering_actor }}@gmail.com
          git checkout -b $OUTPUT_BRANCH
          
          find . -type f ! -name "$OUTPUT" -not -path './.git/*' -delete
          rm -rf node_modules
          
          git init
          git add .
          git commit -m "Compile ${{ github.event.repository.name }} SCSS v${{ env.VERSION }} build #${{ github.run_number }}"
          git push -f origin $OUTPUT_BRANCH

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: ${{ env.VERSION }}
          prerelease: false
          title: "${{ github.event.repository.name }} v${{ env.VERSION }}"
          files: ${{ env.OUTPUT }}
